// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type DeviceInfo struct {
	Version   string  `json:"version"`
	SetupStep int     `json:"setupStep"`
	BaseImage string  `json:"baseImage"`
	CPU       string  `json:"cpu"`
	IsDocker  bool    `json:"isDocker"`
	State     *string `json:"state"`
	Chain     *string `json:"chain"`
	Network   *string `json:"network"`
	Message   *string `json:"message"`
	HostName  *string `json:"hostName"`
}

// The `LoginInput` type represents the required login input
type LoginInput struct {
	// The `username` can either be an email or the actual username
	Username string `json:"username"`
	// The `password` length must be 8 characters minimum
	Password string `json:"password"`
}

type RegisterInput struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdatedDeviceInfo struct {
	SetupStep *int    `json:"setupStep"`
	State     *string `json:"state"`
	Chain     *string `json:"chain"`
	Network   *string `json:"network"`
	Message   *string `json:"message"`
	HostName  *string `json:"hostName"`
}
