// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type BlitzDeviceInfo struct {
	Version string `json:"version"`
}

// The `LoginInput` type represents the required login input
type LoginInput struct {
	// The `username` can either be an email or the actual username
	Username string `json:"username"`
	// The `password` length must be 8 characters minimum
	Password string `json:"password"`
}

type PushSetupEventMessage struct {
	// The state of this setup event
	State int `json:"state"`
	// A message associated with this event
	Message string `json:"message"`
}

type RegisterInput struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type SetupInfoEvent struct {
	// The state of this setup event
	State int `json:"state"`
	// A message associated with this event
	Message string `json:"message"`
}
